### ISSUE TITLE
Half-rating in rtl

### ISSUE THREAD

**Issue by alonat** [craigh411/vue-rate-it#10]
Hello!
If I use rating on rtl with increment 1, I haven't any problems.
But if I want to use increment less than 1 I have a problem like in an image
![image](https://user-images.githubusercontent.com/22292953/31810692-5bc004c0-b585-11e7-878b-be81093e2d19.png)

**Comment by craigh411** [comment]
I've implemented this on [vue-star-rating](https://github.com/craigh411/vue-star-rating) and it's definitely on the roadmap for this component as a priority. Hopefully, I will get this done as soon as I've sorted out the package size.

**Comment by craigh411** [comment]
@alonat RTL has now been implemented across all the components, so you should no longer have this issue in [version 2.1.0](https://github.com/craigh411/vue-rate-it/releases/tag/v2.1.0)
