### ISSUE TITLE
usage without webpack

### ISSUE THREAD

**Issue by nise** [craigh411/vue-rate-it#15]
This requirement makes the module not usable without having webpack at hand:
```

(function webpackUniversalModuleDefinition(root, factory) {
	...
})(this, function(__WEBPACK_EXTERNAL_MODULE_1__) {
```
Hence, not every one uses webpack together with vue.js

Therefore, I would consider it as a bug.

**Comment by craigh411** [comment]
Are you experiencing problems with this? As far as I'm aware, this is just how `webpack` bundles the file, however,  it's output as a UMD module and there should be no requirement to have `webpack` in your build process. It certainly works with `browserify` and each component is also available via CDN (or as dist files) and ready to run, as seen here: https://jsfiddle.net/craig_h_411/zhjxuorw/
