### ISSUE TITLE
Problem transpiling with Webpack

### ISSUE THREAD

**Issue by zhangwei900808** [craigh411/vue-rate-it#3]
Receiving the following error:

>ERROR in static/js/vendor.a59ada575940efd41518.js from UglifyJs Unexpected token punc «(», expected punc «:» [./~/vue-rate-it/src/mixins/RatingItem.js:42,0][static/js/vendor.a59ada575940efd41518.js:12454,11]

![image](https://cloud.githubusercontent.com/assets/4385154/25737168/df029930-31a8-11e7-8564-7fe4947e938e.png)

**Comment by craigh411** [comment]
You need to make sure that you are not excluding `babel-loader` from transpiling vue-rate-it. You can find the full docs at: https://craigh411.github.io/vue-rate-it

But specifically you need to make sure you have the following in your `webpack.config.js` file:

```
module: {
  rules: [{
    test: /\.vue$/,
    loader: 'vue-loader',
  }, {
    test: /\.js$/,
    loader: 'babel-loader',
    exclude: /node_modules\/(?!(vue-rate-it)\/).*/
  }
  }]
}
```

**Comment by zhangwei900808** [comment]
I'm sure I including babel-loader add exclude in the webpack but still error.And my webpack project used from Vue-Cli and you can try it

**Comment by craigh411** [comment]
I've just got this working with webpack simple without any problems, here are the steps I took:

- `vue init webpack-simple vue-rate-it-webpack`
- `cd vue-rate-it-webpack`
- `npm install`
- `npm install vue-rate-it --save-dev`

Then, in `webpack.config.js` I changed:

```
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      }
```

to:

```
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules\/(?!(vue-rate-it)\/).*/
      }
```

**If I don't do this, I receive the exact error you are describing.**

Then I imported `StarRating` into `App.vue` and added it as a component and run:

- `npm run build`

and it compiles fine.

If you post your `webpack.config.js` I can take a look at it for you.

**Comment by zhangwei900808** [comment]
Ok,next week I send to you. Please wait for me

**Comment by craigh411** [comment]
OK, I've now taken the hit my end and am pre-transpiling the mixins, so there should no longer be any need to mess with the webpack config.

It's a bit tricky because `vue-loader` automatically applies the babel transform to `.vue` files but not to any mixins, I'll have a think about if there is a better way to approach this problem but for now this should be resolved.

**Comment by craigh411** [comment]
I've now added a bundled umd module in version 1.1.4 and added this as the entry point, so there is no longer any need to worry about `webpack config` or even having `vue-loader` or `babel-loader` in your project as the component is now pre-transpiled. This should make it much easier to import into your projects.
