### ISSUE TITLE
SEO concerns

### ISSUE THREAD

**Issue by hdl-helsinki** [craigh411/vue-rate-it#4]
Hello,

The plugin creates a `div` inside a `span`.

example:

```html
<span data-v-217e3548="" class="pointer rating-item">
    <div data-v-217e3916="" step="100" style="display: inline-block; margin-right: 1px;">
        <svg width="21" height="21"> ... </svg>
   </div>
</span>
```

Could the div be replaced by a span?

Thank you.

**Comment by craigh411** [comment]
Good spot. I will get that sorted out ASAP.

**Comment by craigh411** [comment]
Fixed this now. I replaced the `span` with a `div` simply because it prevents this issue from reoccurring in future.

**Comment by hdl-helsinki** [comment]
Thank you @craigh411

**Comment by hdl-helsinki** [comment]
Thank you @craigh411
