### ISSUE TITLE
import {StarRating} from 'vue-rate-it'; still imports all rating types.

### ISSUE THREAD

**Issue by lsascha** [craigh411/vue-rate-it#7]
Hello,
sorry that i open another issue.
But i am having trouble at the moment only importing the StarRating component.

According to the documentation i have to use
> import {StarRating} from 'vue-rate-it';

that works, however in the final webpack compiled javascript file, all rating components are included which makes the file unnecessary big.

I can do
> import StarRating from 'vue-rate-it/src/raters/stars/star-rating.vue';

however with that UglifyJs has issues and breaks with the error:
```
[15:58:38] Error (webpack-stream): main.js from UglifyJs
Unexpected token: punc (() [main.js:27141,11]
[15:58:38] Version: webpack 3.2.0
                                               Asset    Size  Chunks                    Chunk Names
                                             main.js  796 kB       0  [emitted]  [big]  main
/Resources/Private/Styles/vuestyles/_main.style.scss  2.2 kB       0  [emitted]         main

ERROR in main.js from UglifyJs
Unexpected token: punc (() [main.js:27141,11]
```

Could be of course an issue with my configuration, but so far that is the only 3rd party component that makes this problems.

without UglifyJs everything works when importing with
> import StarRating from 'vue-rate-it/src/raters/stars/star-rating.vue';

Any ideas?

Thanks in advance

**Comment by craigh411** [comment]
Hmm, I agree that's a bit of a pain, and honestly I would have thought webpack would have only imported the individual module member being used, but apparently this is not the case. 

If you want to bundle the file yourself then you need to make sure that `babel-loader` is not ignoring `vue-rate-it` in `node_modules`, so at the moment I assume you have something like this in your webpack config:

```
module: {
  rules: [
    {
      test: /\.js$/,
      loader: 'babel-loader',
      exclude: /node_modules/
    }
  ]
}
```

This tells `babel-loader` to ignore everything in `node_modules`, but it needs to be applied to `vue-rate-it`  to correctly transpile the `mixins`, so you will need to modify the exclude to:

```
module: {
  rules: [
    {
      test: /\.js$/,
      loader: 'babel-loader',
      exclude: /node_modules\/(?!(vue-rate-it)\/).*/
    }
  ]
}
```
Which simply tells `babel-loader` to ignore everything in `node_modules` except `vue-rate-it`.

Alternatively, if you just want the stars, I also maintain a separate repo for that component (which is how `vue-rate-it` began), which you can find at: https://github.com/craigh411/vue-star-rating

**Comment by lsascha** [comment]
thanks. setting exclude to `/node_modules\/(?!(vue-rate-it)).*/`
worked after i fixed some other babel configuration that i missed for a js feature i used.
